version: '3.8'

services:
  auth-db:
    image: postgres:14
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    volumes:
      - ./init/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-redis:
    image: redis:7
    ports:
      - "6379:6379"

  converter-db:
    image: mongo:5
    environment:
      MONGO_INITDB_DATABASE: converter_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - ./init/mongo/init.js:/docker-entrypoint-initdb.d/init.js
      - converter-db-data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  auth-db-data:
  converter-db-data: